packages:
  - apps/*
  - packages/*
  - tools/*
  - examples/workspace/*

catalog:
  "@pinia/colada": ^1.1.0
  "@mariozechner/pi-agent-core": ^0.62.0
  "@mariozechner/pi-ai": ^0.62.0
  "@mariozechner/pi-tui": ^0.63.1
  "@sinclair/typebox": ^0.34.48
  "@tailwindcss/vite": ^4.2.2
  "@tailwindcss/typography": ^0.5.16
  "@types/node": ^24.12.0
  "@vueuse/core": ^14.2.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  dotenv: ^17.3.1
  glob: ^13.0.6
  lucide-vue-next: ^1.0.0
  playwright: ^1.59.1
  reka-ui: ^2.9.3
  shadcn-vue: ^2.5.1
  tailwind-merge: ^3.5.0
  tailwindcss: ^4.2.2
  tsx: ^4.21.0
  tw-animate-css: ^1.4.0
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plugin-vue-devtools: ^8.1.1
  vite-plus: 0.1.13
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  yaml: ^2.8.3

catalogMode: prefer
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
